"""initial schema

Revision ID: 698141e0a22e
Revises: 
Create Date: 2026-06-29 16:30:24.343999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698141e0a22e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('dsl', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_policy_name_version')
    )
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('output_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('verdict', sa.Enum('ALLOW', 'BLOCK', 'TRANSFORM', name='verdict'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_table('audit_entries',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('prev_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('entry_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('signature', sa.LargeBinary(length=64), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('decision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
